In [2]:
import pandas as pd
import mysql.connector
import pymongo

In [17]:
df = pd.read_csv('../../FSDS_DATA_SET/atribute.csv')

In [18]:
df.head()

Dress_ID    Style    Price  Rating Size  Season NeckLine SleeveLength  \
0  1006032852     Sexy      Low     4.6    M  Summer   o-neck    sleevless   
1  1212192089   Casual      Low     0.0    L  Summer   o-neck        Petal   
2  1190380701  vintage     High     0.0    L  Automn   o-neck         full   
3   966005983    Brief  Average     4.6    L  Spring   o-neck         full   
4   876339541     cute      Low     4.5    M  Summer   o-neck    butterfly   

  waiseline       Material FabricType  Decoration Pattern Type  Recommendation  
0    empire            NaN    chiffon     ruffles       animal               1  
1   natural     microfiber        NaN     ruffles       animal               0  
2   natural       polyster        NaN         NaN        print               0  
3   natural           silk    chiffon  embroidary        print               1  
4   natural  chiffonfabric    chiffon         bow          dot               0

In [19]:
# CONVERTING ATTRIBUTE DATASET INTO JSON FILE
df.to_json('../../FSDS_DATA_SET/attribute.json')

In [20]:
# Reading JSON file into df_json
df_json = pd.read_json('../../FSDS_DATA_SET/attribute.json')

In [21]:
df_json.head()

Dress_ID    Style    Price  Rating Size  Season NeckLine SleeveLength  \
0  1006032852     Sexy      Low     4.6    M  Summer   o-neck    sleevless   
1  1212192089   Casual      Low     0.0    L  Summer   o-neck        Petal   
2  1190380701  vintage     High     0.0    L  Automn   o-neck         full   
3   966005983    Brief  Average     4.6    L  Spring   o-neck         full   
4   876339541     cute      Low     4.5    M  Summer   o-neck    butterfly   

  waiseline       Material FabricType  Decoration Pattern Type  Recommendation  
0    empire           None    chiffon     ruffles       animal               1  
1   natural     microfiber       None     ruffles       animal               0  
2   natural       polyster       None        None        print               0  
3   natural           silk    chiffon  embroidary        print               1  
4   natural  chiffonfabric    chiffon         bow          dot               0

In [22]:
# Login Credentials for MYSql server
host_name = 'localhost'
user_name = 'root'
password = '<your password>'

In [23]:
try:
    connection = mysql.connector.connect(host=host_name, user = user_name, password=password, use_pure=True, auth_plugin='mysql_native_password')
except Exception as e:
    print(f"Exception => {e}")
    

In [24]:
cursor = connection.cursor()


In [25]:
query_databses = """
    SHOW DATABASES
"""

In [26]:
cursor.execute(query_databses)
print(cursor.fetchall())

[('bank',), ('Days-30',), ('dummytest',), ('information_schema',), ('mysql',), ('node-complete',), ('performance_schema',), ('practice',), ('sys',)]


In [27]:
print(cursor)

MySQLCursor: 
    SHOW DATABASES



In [28]:
all_columns = """ 
    SELECT DISTINCT TABLE_NAME FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'dummytest' 
"""

cursor.execute(all_columns)
print(cursor.fetchall())

[('attribute',), ('dressSales',), ('ui_attribute',), ('ui_sales',)]


In [29]:
left_join_query = """
    SELECT attr.Dress_Id FROM dummytest.ui_attribute as attr
left join dummytest.ui_sales as sales
on sales.Dress_Id = attr.Dress_id;
"""

cursor.execute(left_join_query)
print(len(cursor.fetchall()))

550


In [30]:
sales_table = """
    SELECT * FROM dummytest.ui_sales
    limit 10
"""

cursor.execute(sales_table)
print(cursor.fetchall())

[(1006032852, 2114, 2274, 2491, 2660, 2727, 2887, 2930, 3119, 3204, 3277, 3321, 3386, 3479, 3554, 3624.0, 3706, 3746.0, 3795.0, 3832.0, 3897, 3923.0, 3985.0, 4048), (1212192089, 151, 275, 570, 750, 813, 1066, 1164, 1558, 1756, 1878, 1985, 2106, 2454, 2710, 2942.0, 3258, 3354.0, 3475.0, 3654.0, 3911, 4024.0, 4125.0, 4277), (1190380701, 6, 7, 7, 7, 8, 8, 9, 10, 10, 10, 10, 10, 11, 11, 11.0, 11, 11.0, 11.0, 11.0, 11, 11.0, 11.0, 11), (966005983, 1005, 1128, 1326, 1455, 1507, 1621, 1637, 1723, 1746, 1783, 1796, 1812, 1845, 1878, 1892.0, 1914, 1924.0, 1929.0, 1941.0, 1952, 1955.0, 1959.0, 1963), (876339541, 996, 1175, 1304, 1396, 1432, 1559, 1570, 1638, 1655, 1681, 1743, 1824, 1919, 2032, 2156.0, 2252, 2312.0, 2387.0, 2459.0, 2544, 2614.0, 2693.0, 2736), (1068332458, 4, 5, 11, 13, 13, 13, 16, 18, 19, 20, 20, 21, 22, 25, 25.0, 26, 26.0, 26.0, 26.0, 27, 27.0, 27.0, 27), (1220707172, 45, 61, 131, 165, 176, 209, 216, 251, 262, 289, 295, 325, 353, 379, 400.0, 417, 424.0, 445.0, 462.0, 474, 494.0

In [31]:
# Reading SQL data into a Dataframe
sales_data = """
    SELECT * FROM dummytest.ui_sales
"""

cursor.execute(sales_data)
result = cursor.fetchall()

In [32]:
df_sales = pd.DataFrame(result)

In [33]:
df_sales.head()

0     1     2     3     4     5     6     7     8     9   ...  \
0  1006032852  2114  2274  2491  2660  2727  2887  2930  3119  3204  ...   
1  1212192089   151   275   570   750   813  1066  1164  1558  1756  ...   
2  1190380701     6     7     7     7     8     8     9    10    10  ...   
3   966005983  1005  1128  1326  1455  1507  1621  1637  1723  1746  ...   
4   876339541   996  1175  1304  1396  1432  1559  1570  1638  1655  ...   

     14      15    16      17      18      19    20      21      22    23  
0  3554  3624.0  3706  3746.0  3795.0  3832.0  3897  3923.0  3985.0  4048  
1  2710  2942.0  3258  3354.0  3475.0  3654.0  3911  4024.0  4125.0  4277  
2    11    11.0    11    11.0    11.0    11.0    11    11.0    11.0    11  
3  1878  1892.0  1914  1924.0  1929.0  1941.0  1952  1955.0  1959.0  1963  
4  2032  2156.0  2252  2312.0  2387.0  2459.0  2544  2614.0  2693.0  2736  

[5 rows x 24 columns]

In [34]:
df_sales_sql = pd.read_sql('SELECT * FROM dummytest.ui_sales', con=connection)

In [35]:
df_sales_sql.head()

Dress_ID  29/8/2013  31/8/2013  2013-02-09 00:00:00  2013-04-09 00:00:00  \
0  1006032852       2114       2274                 2491                 2660   
1  1212192089        151        275                  570                  750   
2  1190380701          6          7                    7                    7   
3   966005983       1005       1128                 1326                 1455   
4   876339541        996       1175                 1304                 1396   

   2013-06-09 00:00:00  2013-08-09 00:00:00  2013-10-09 00:00:00  \
0                 2727                 2887                 2930   
1                  813                 1066                 1164   
2                    8                    8                    9   
3                 1507                 1621                 1637   
4                 1432                 1559                 1570   

   2013-12-09 00:00:00  14/9/2013  ...  24/9/2013  26/9/2013  28/9/2013  \
0                 3119       3204  ...       3554     3624.0       3706   
1                 1558       1756  ...       2710     2942.0       3258   
2                   10         10  ...         11       11.0         11   
3                 1723       1746  ...       1878     1892.0       1914   
4                 1638       1655  ...       2032     2156.0       2252   

   30/9/2013  2013-02-10 00:00:00  2013-04-10 00:00:00  2013-06-10 00:00:00  \
0     3746.0               3795.0               3832.0                 3897   
1     3354.0               3475.0               3654.0                 3911   
2       11.0                 11.0                 11.0                   11   
3     1924.0               1929.0               1941.0                 1952   
4     2312.0               2387.0               2459.0                 2544   

   2010-08-10 00:00:00  2013-10-10 00:00:00  2013-12-10 00:00:00  
0               3923.0               3985.0                 4048  
1               4024.0               4125.0                 4277  
2                 11.0                 11.0                   11  
3               1955.0               1959.0                 1963  
4               2614.0               2693.0                 2736  

[5 rows x 24 columns]

In [36]:
# READING DATA FROM MYSQL DATABASE    
df_attributes_sql = pd.read_sql("SELECT * FROM dummytest.ui_attribute", con=connection)

In [37]:
df_attributes_sql.tail()

Dress_ID   Style    Price  Rating  Size  Season   NeckLine SleeveLength  \
495  713391965  Casual      Low     4.7     M  Spring     o-neck         full   
496  722565148    Sexy      Low     4.3  free  Summer     o-neck         full   
497  532874347  Casual  Average     4.7     M  Summer     v-neck         full   
498  655464934  Casual  Average     4.6     L  winter  boat-neck    sleevless   
499  919930954  Casual      Low     4.4  free  Summer     v-neck        short   

    waiseline  Material  FabricType Decoration Pattern Type  Recommendation  
495   natural  polyster                               solid               1  
496    empire    cotton                                                   0  
497    empire    cotton                   lace        solid               1  
498    empire      silk  broadcloth   applique        print               1  
499    empire    cotton    Corduroy       lace        solid               0

In [38]:
type(df_attributes_sql)

pandas.core.frame.DataFrame

In [39]:
# Applying left join using pandas
pd.merge(left=df_attributes_sql, right=df_sales_sql, how='left', left_on='Dress_ID', right_on='Dress_ID')

Dress_ID    Style    Price  Rating  Size  Season   NeckLine  \
0    1006032852     Sexy      Low     4.6     M  Summer     o-neck   
1    1212192089   Casual      Low     0.0     L  Summer     o-neck   
2    1190380701  vintage     High     0.0     L  Automn     o-neck   
3     966005983    Brief  Average     4.6     L  Spring     o-neck   
4     876339541     cute      Low     4.5     M  Summer     o-neck   
..          ...      ...      ...     ...   ...     ...        ...   
545   722565148     Sexy      Low     4.3  free  Summer     o-neck   
546   722565148     Sexy      Low     4.3  free  Summer     o-neck   
547   532874347   Casual  Average     4.7     M  Summer     v-neck   
548   655464934   Casual  Average     4.6     L  winter  boat-neck   
549   919930954   Casual      Low     4.4  free  Summer     v-neck   

    SleeveLength waiseline       Material  ... 24/9/2013 26/9/2013 28/9/2013  \
0      sleevless    empire                 ...    3554.0    3624.0    3706.0   
1          Petal   natural     microfiber  ...    2710.0    2942.0    3258.0   
2           full   natural       polyster  ...      11.0      11.0      11.0   
3           full   natural           silk  ...    1878.0    1892.0    1914.0   
4      butterfly   natural  chiffonfabric  ...    2032.0    2156.0    2252.0   
..           ...       ...            ...  ...       ...       ...       ...   
545         full    empire         cotton  ...     859.0       0.0     882.0   
546         full    empire         cotton  ...     859.0     866.0     882.0   
547         full    empire         cotton  ...     616.0     597.0     586.0   
548    sleevless    empire           silk  ...     257.0     256.0     255.0   
549        short    empire         cotton  ...     628.0     632.0     639.0   

     30/9/2013  2013-02-10 00:00:00  2013-04-10 00:00:00  2013-06-10 00:00:00  \
0       3746.0               3795.0               3832.0               3897.0   
1       3354.0               3475.0               3654.0               3911.0   
2         11.0                 11.0                 11.0                 11.0   
3       1924.0               1929.0               1941.0               1952.0   
4       2312.0               2387.0               2459.0               2544.0   
..         ...                  ...                  ...                  ...   
545        0.0                  0.0                  0.0                906.0   
546      888.0                895.0                898.0                906.0   
547      569.0                561.0                555.0                551.0   
548      254.0                253.0                250.0                249.0   
549      645.0                651.0                655.0                660.0   

     2010-08-10 00:00:00  2013-10-10 00:00:00  2013-12-10 00:00:00  
0                 3923.0               3985.0               4048.0  
1                 4024.0               4125.0               4277.0  
2                   11.0                 11.0                 11.0  
3                 1955.0               1959.0               1963.0  
4                 2614.0               2693.0               2736.0  
..                   ...                  ...                  ...  
545                  0.0                  0.0                931.0  
546                913.0                919.0                931.0  
547                546.0                535.0                520.0  
548                249.0                249.0                248.0  
549                668.0                674.0                680.0  

[550 rows x 37 columns]

# UNIQUE DRESSES

In [40]:
# using SQL query
query_unique_dresses = """
    select distinct dress_id from dummytest.ui_attribute
"""

cursor.execute(query_unique_dresses)
print(len(cursor.fetchall()))

475


In [41]:
# using pandas
df_attributes_sql['Dress_ID'].nunique()

475

WE HAVE A TOTAL OF 475 UNIQUE DRESSES

In [42]:
# WE HAVE A TOTAL OF 475 UNIQUE DRESSES

# Dresses with recommendation 0

In [43]:
# using SQL query
query_0_recommendation = """
    SELECT COUNT(Dress_ID) FROM dummytest.ui_attribute
    WHERE recommendation = 0 
"""

cursor.execute(query_0_recommendation)
print(cursor.fetchall())

[(290,)]


In [44]:
# using pandas
df_attributes_sql.query('Recommendation == 0')

Dress_ID     Style    Price  Rating  Size  Season NeckLine  \
1    1212192089    Casual      Low     0.0     L  Summer   o-neck   
2    1190380701   vintage     High     0.0     L  Automn   o-neck   
4     876339541      cute      Low     4.5     M  Summer   o-neck   
5    1068332458  bohemian      Low     0.0     M  Summer   v-neck   
6    1220707172    Casual  Average     0.0    XL  Summer   o-neck   
..          ...       ...      ...     ...   ...     ...      ...   
490   641665398    Casual      Low     4.8  free  winter  bowneck   
492   859922576      cute  Average     4.6     M  Spring   o-neck   
494   990559192     Brief  Average     4.7     M  winter   o-neck   
496   722565148      Sexy      Low     4.3  free  Summer   o-neck   
499   919930954    Casual      Low     4.4  free  Summer   v-neck   

    SleeveLength waiseline       Material FabricType Decoration Pattern Type  \
1          Petal   natural     microfiber               ruffles       animal   
2           full   natural       polyster                              print   
4      butterfly   natural  chiffonfabric    chiffon        bow          dot   
5      sleevless    empire                                             print   
6           full                   cotton                              solid   
..           ...       ...            ...        ...        ...          ...   
490         full   natural       polyster    chiffon        bow        solid   
492   halfsleeve   natural        acrylic    chiffon                           
494   halfsleeve   natural        acrylic    chiffon                 striped   
496         full    empire         cotton                                      
499        short    empire         cotton   Corduroy       lace        solid   

     Recommendation  
1                 0  
2                 0  
4                 0  
5                 0  
6                 0  
..              ...  
490               0  
492               0  
494               0  
496               0  
499               0  

[290 rows x 14 columns]

290 Dresses are present with 0 remmendation

In [45]:
# 290 Dresses are present with 0 remmendation

# Sale for each Dress ID

In [46]:
df_sales_sql.shape

(498, 24)

In [47]:
df_sales_sql.sample(5)

Dress_ID  29/8/2013  31/8/2013  2013-02-09 00:00:00  \
450   605122868          0          0                    0   
160  1246749980          7          8                   30   
214  1097157656        111        122                  139   
460  1097157656          0          0                    0   
441  1249825438          0          0                    0   

     2013-04-09 00:00:00  2013-06-09 00:00:00  2013-08-09 00:00:00  \
450                  239                  239                  233   
160                   48                   57                  109   
214                  146                  156                  167   
460                  142                  156                  167   
441                   41                   50                   63   

     2013-10-09 00:00:00  2013-12-09 00:00:00  14/9/2013  ...  24/9/2013  \
450                  228                  224        224  ...        210   
160                  137                  226        243  ...        736   
214                  168                  168        168  ...        176   
460                  168                  168        168  ...        176   
441                   66                   73         75  ...        101   

     26/9/2013  28/9/2013  30/9/2013  2013-02-10 00:00:00  \
450      208.0        205      201.0                294.0   
160        0.0        922        0.0                  0.0   
214        0.0        181        0.0                  0.0   
460      178.0        181      183.0                185.0   
441      103.0        105      107.0                109.0   

     2013-04-10 00:00:00  2013-06-10 00:00:00  2010-08-10 00:00:00  \
450                291.0                  189                185.0   
160                  0.0                 1143                  0.0   
214                  0.0                  188                  0.0   
460                186.0                  188                189.0   
441                111.0                  113                115.0   

     2013-10-10 00:00:00  2013-12-10 00:00:00  
450                180.0                  178  
160                  0.0                 1288  
214                  0.0                  190  
460                189.0                  190  
441                116.0                  117  

[5 rows x 24 columns]

In [48]:
df_sales_sql.columns

Index(['Dress_ID', '29/8/2013', '31/8/2013', '2013-02-09 00:00:00',
       '2013-04-09 00:00:00', '2013-06-09 00:00:00', '2013-08-09 00:00:00',
       '2013-10-09 00:00:00', '2013-12-09 00:00:00', '14/9/2013', '16/9/2013',
       '18/9/2013', '20/9/2013', '22/9/2013', '24/9/2013', '26/9/2013',
       '28/9/2013', '30/9/2013', '2013-02-10 00:00:00', '2013-04-10 00:00:00',
       '2013-06-10 00:00:00', '2010-08-10 00:00:00', '2013-10-10 00:00:00',
       '2013-12-10 00:00:00'],
      dtype='object')

In [49]:
sales_numbers = df_sales_sql.drop('Dress_ID',axis=1)
sales_numbers.tail()

29/8/2013  31/8/2013  2013-02-09 00:00:00  2013-04-09 00:00:00  \
493          0          0                    0                  560   
494          0          0                    0                  875   
495          0          0                    0                  734   
496          0          0                    0                  254   
497          0          0                    0                  538   

     2013-06-09 00:00:00  2013-08-09 00:00:00  2013-10-09 00:00:00  \
493                  554                  544                  537   
494                  866                  861                  854   
495                  728                  726                  715   
496                  259                  261                  263   
497                  545                  558                  563   

     2013-12-09 00:00:00  14/9/2013  16/9/2013  ...  24/9/2013  26/9/2013  \
493                  525        519        511  ...        400      388.0   
494                  850        844        841  ...        859      866.0   
495                  694        690        686  ...        616      597.0   
496                  268        270        272  ...        257      256.0   
497                  578        585        590  ...        628      632.0   

     28/9/2013  30/9/2013  2013-02-10 00:00:00  2013-04-10 00:00:00  \
493        360      364.0                372.0                377.0   
494        882      888.0                895.0                898.0   
495        586      569.0                561.0                555.0   
496        255      254.0                253.0                250.0   
497        639      645.0                651.0                655.0   

     2013-06-10 00:00:00  2010-08-10 00:00:00  2013-10-10 00:00:00  \
493                  380                382.0                384.0   
494                  906                913.0                919.0   
495                  551                546.0                535.0   
496                  249                249.0                249.0   
497                  660                668.0                674.0   

     2013-12-10 00:00:00  
493                  285  
494                  931  
495                  520  
496                  248  
497                  680  

[5 rows x 23 columns]

In [50]:
unique_dresses_sales = df_sales_sql.groupby('Dress_ID').sum()
unique_dresses_sales[unique_dresses_sales.index==905732124]
# temp.head()

29/8/2013  31/8/2013  2013-02-09 00:00:00  2013-04-09 00:00:00  \
Dress_ID                                                                    
905732124         65         79                   90                  194   

           2013-06-09 00:00:00  2013-08-09 00:00:00  2013-10-09 00:00:00  \
Dress_ID                                                                   
905732124                  200                  218                  224   

           2013-12-09 00:00:00  14/9/2013  16/9/2013  ...  24/9/2013  \
Dress_ID                                              ...              
905732124                  252        261        280  ...        382   

           26/9/2013  28/9/2013  30/9/2013  2013-02-10 00:00:00  \
Dress_ID                                                          
905732124        0.0        418        0.0                  0.0   

           2013-04-10 00:00:00  2013-06-10 00:00:00  2010-08-10 00:00:00  \
Dress_ID                                                                   
905732124                  0.0                  510                  0.0   

           2013-10-10 00:00:00  2013-12-10 00:00:00  
Dress_ID                                             
905732124                  0.0                  570  

[1 rows x 23 columns]

In [51]:
df_sales_sql[df_sales_sql['Dress_ID']==905732124]

Dress_ID  29/8/2013  31/8/2013  2013-02-09 00:00:00  \
225  905732124         65         79                   90   
335  905732124          0          0                    0   

     2013-04-09 00:00:00  2013-06-09 00:00:00  2013-08-09 00:00:00  \
225                   98                  100                  109   
335                   96                  100                  109   

     2013-10-09 00:00:00  2013-12-09 00:00:00  14/9/2013  ...  24/9/2013  \
225                  112                  126        128  ...        191   
335                  112                  126        133  ...        191   

     26/9/2013  28/9/2013  30/9/2013  2013-02-10 00:00:00  \
225        0.0        209        0.0                  0.0   
335        0.0        209        0.0                  0.0   

     2013-04-10 00:00:00  2013-06-10 00:00:00  2010-08-10 00:00:00  \
225                  0.0                  255                  0.0   
335                  0.0                  255                  0.0   

     2013-10-10 00:00:00  2013-12-10 00:00:00  
225                  0.0                  285  
335                  0.0                  285  

[2 rows x 24 columns]

In [52]:
df_sales_sql.head()

Dress_ID  29/8/2013  31/8/2013  2013-02-09 00:00:00  2013-04-09 00:00:00  \
0  1006032852       2114       2274                 2491                 2660   
1  1212192089        151        275                  570                  750   
2  1190380701          6          7                    7                    7   
3   966005983       1005       1128                 1326                 1455   
4   876339541        996       1175                 1304                 1396   

   2013-06-09 00:00:00  2013-08-09 00:00:00  2013-10-09 00:00:00  \
0                 2727                 2887                 2930   
1                  813                 1066                 1164   
2                    8                    8                    9   
3                 1507                 1621                 1637   
4                 1432                 1559                 1570   

   2013-12-09 00:00:00  14/9/2013  ...  24/9/2013  26/9/2013  28/9/2013  \
0                 3119       3204  ...       3554     3624.0       3706   
1                 1558       1756  ...       2710     2942.0       3258   
2                   10         10  ...         11       11.0         11   
3                 1723       1746  ...       1878     1892.0       1914   
4                 1638       1655  ...       2032     2156.0       2252   

   30/9/2013  2013-02-10 00:00:00  2013-04-10 00:00:00  2013-06-10 00:00:00  \
0     3746.0               3795.0               3832.0                 3897   
1     3354.0               3475.0               3654.0                 3911   
2       11.0                 11.0                 11.0                   11   
3     1924.0               1929.0               1941.0                 1952   
4     2312.0               2387.0               2459.0                 2544   

   2010-08-10 00:00:00  2013-10-10 00:00:00  2013-12-10 00:00:00  
0               3923.0               3985.0                 4048  
1               4024.0               4125.0                 4277  
2                 11.0                 11.0                   11  
3               1955.0               1959.0                 1963  
4               2614.0               2693.0                 2736  

[5 rows x 24 columns]

In [53]:
sales_numbers.sample(4)

29/8/2013  31/8/2013  2013-02-09 00:00:00  2013-04-09 00:00:00  \
331          0          0                    0                   81   
201         28         38                   51                   55   
416          0          0                    0                   39   
361          0          0                    0                   30   

     2013-06-09 00:00:00  2013-08-09 00:00:00  2013-10-09 00:00:00  \
331                   82                  102                  106   
201                   55                   61                   66   
416                   39                   40                   41   
361                   32                   36                   37   

     2013-12-09 00:00:00  14/9/2013  16/9/2013  ...  24/9/2013  26/9/2013  \
331                  119        124        134  ...        162        0.0   
201                   74         76         79  ...        119        0.0   
416                   43         43         43  ...         44       44.0   
361                   39         40         41  ...         53       58.0   

     28/9/2013  30/9/2013  2013-02-10 00:00:00  2013-04-10 00:00:00  \
331        167        0.0                  0.0                  0.0   
201        125        0.0                  0.0                  0.0   
416         44       44.0                 46.0                 47.0   
361         61       64.0                 65.0                 68.0   

     2013-06-10 00:00:00  2010-08-10 00:00:00  2013-10-10 00:00:00  \
331                  175                  0.0                  0.0   
201                  155                  0.0                  0.0   
416                   48                 48.0                 48.0   
361                   70                 72.0                 74.0   

     2013-12-10 00:00:00  
331                  182  
201                  175  
416                   48  
361                   75  

[4 rows x 23 columns]

In [54]:
# sales_numbers['total_sales'] = sales_numbers.apply(lambda x : )

In [55]:
df_sales_sql['Dress_ID'] = df_sales_sql['Dress_ID'].apply(lambda x : str(x))
df_sales_sql.tail()

Dress_ID  29/8/2013  31/8/2013  2013-02-09 00:00:00  \
493  713391965          0          0                    0   
494  722565148          0          0                    0   
495  532874347          0          0                    0   
496  655464934          0          0                    0   
497  919930954          0          0                    0   

     2013-04-09 00:00:00  2013-06-09 00:00:00  2013-08-09 00:00:00  \
493                  560                  554                  544   
494                  875                  866                  861   
495                  734                  728                  726   
496                  254                  259                  261   
497                  538                  545                  558   

     2013-10-09 00:00:00  2013-12-09 00:00:00  14/9/2013  ...  24/9/2013  \
493                  537                  525        519  ...        400   
494                  854                  850        844  ...        859   
495                  715                  694        690  ...        616   
496                  263                  268        270  ...        257   
497                  563                  578        585  ...        628   

     26/9/2013  28/9/2013  30/9/2013  2013-02-10 00:00:00  \
493      388.0        360      364.0                372.0   
494      866.0        882      888.0                895.0   
495      597.0        586      569.0                561.0   
496      256.0        255      254.0                253.0   
497      632.0        639      645.0                651.0   

     2013-04-10 00:00:00  2013-06-10 00:00:00  2010-08-10 00:00:00  \
493                377.0                  380                382.0   
494                898.0                  906                913.0   
495                555.0                  551                546.0   
496                250.0                  249                249.0   
497                655.0                  660                668.0   

     2013-10-10 00:00:00  2013-12-10 00:00:00  
493                384.0                  285  
494                919.0                  931  
495                535.0                  520  
496                249.0                  248  
497                674.0                  680  

[5 rows x 24 columns]

In [56]:
df_sales_sql['total_sales'] = df_sales_sql.values[:,1:].sum(axis =1)

In [57]:
df_sales_sql.sample(5)

Dress_ID  29/8/2013  31/8/2013  2013-02-09 00:00:00  \
100   836788720          9         12                   17   
52   1160536550         19         25                   40   
8    1113094204          5          6                   10   
350   774130360          0          0                    0   
336   961230947          0          0                    0   

     2013-04-09 00:00:00  2013-06-09 00:00:00  2013-08-09 00:00:00  \
100                   19                   19                   20   
52                    44                   47                   55   
8                     12                   13                   15   
350                    1                    2                    2   
336                   56                   57                   63   

     2013-10-09 00:00:00  2013-12-09 00:00:00  14/9/2013  ...  26/9/2013  \
100                   20                   22         22  ...       31.0   
52                    56                   59         59  ...       66.0   
8                     16                   17         17  ...       28.0   
350                    2                    2          2  ...        2.0   
336                   65                   70         70  ...       78.0   

     28/9/2013  30/9/2013  2013-02-10 00:00:00  2013-04-10 00:00:00  \
100         31        0.0                  0.0                  0.0   
52          68       68.0                 69.0                 70.0   
8           29       29.0                 29.0                 29.0   
350          2        2.0                  2.0                  2.0   
336         79       80.0                 81.0                 82.0   

     2013-06-10 00:00:00  2010-08-10 00:00:00  2013-10-10 00:00:00  \
100                   31                  0.0                  0.0   
52                    70                 70.0                 71.0   
8                     29                 29.0                 29.0   
350                    2                  3.0                  3.0   
336                   83                 85.0                 86.0   

     2013-12-10 00:00:00  total_sales  
100                   35        426.0  
52                    71       1341.0  
8                     33        494.0  
350                    3         42.0  
336                   88       1490.0  

[5 rows x 25 columns]

In [58]:
df_sales_sql[['Dress_ID','total_sales']].sort_values(by='total_sales',ascending=False)

Dress_ID total_sales
29    629131530    155927.0
46    735635595     91556.0
0    1006032852     75979.0
13    749031896     75346.0
109   737538048     57543.0
..          ...         ...
396  1139064593        20.0
453   898316315        20.0
399   703395323        20.0
468  1124754999        19.0
428   907669618         4.0

[498 rows x 2 columns]

In [59]:
individual_dress_sale = df_sales_sql.groupby('Dress_ID').aggregate({'total_sales':sum})

In [147]:
individual_dress_sale.head(10)

total_sales
Dress_ID               
1000425584       1077.0
1000493051       9852.0
1001750851        410.0
1002440915       1843.0
1004212992      48440.0
1006032852      75979.0
1010356223       1070.0
1015249105       5205.0
1016250560       5621.0
1017484769        690.0

# Third highest most selling dress

In [61]:
df_sales_sql.groupby('Dress_ID').aggregate({'total_sales':sum}).sort_values(by='total_sales',ascending=False).iloc[2]

total_sales    75979.0
Name: 1006032852, dtype: float64

In [62]:
individual_dress_sale.sort_values(by='total_sales',ascending=False).iloc[2]

total_sales    75979.0
Name: 1006032852, dtype: float64

In [63]:
df_sales_sql[df_sales_sql['Dress_ID']== '1006032852']

Dress_ID  29/8/2013  31/8/2013  2013-02-09 00:00:00  2013-04-09 00:00:00  \
0  1006032852       2114       2274                 2491                 2660   

   2013-06-09 00:00:00  2013-08-09 00:00:00  2013-10-09 00:00:00  \
0                 2727                 2887                 2930   

   2013-12-09 00:00:00  14/9/2013  ...  26/9/2013  28/9/2013  30/9/2013  \
0                 3119       3204  ...     3624.0       3706     3746.0   

   2013-02-10 00:00:00  2013-04-10 00:00:00  2013-06-10 00:00:00  \
0               3795.0               3832.0                 3897   

   2010-08-10 00:00:00  2013-10-10 00:00:00  2013-12-10 00:00:00  total_sales  
0               3923.0               3985.0                 4048      75979.0  

[1 rows x 25 columns]

In [64]:
individual_dress_sale[individual_dress_sale.index == '1006032852']

total_sales
Dress_ID               
1006032852      75979.0

Third highest most selling dress is with DressID = 1006032852 and total sale made is 75979.0

In [65]:
cursor.close()
connection.close()

# Storing Attribute and Sales Data set in mongoDb Server (JSON format)

In [140]:
attr_df_json = pd.read_json('../../FSDS_DATA_SET/attribute.json')
attr_df_json.tail()

Dress_ID   Style    Price  Rating  Size  Season   NeckLine SleeveLength  \
495  713391965  Casual      Low     4.7     M  Spring     o-neck         full   
496  722565148    Sexy      Low     4.3  free  Summer     o-neck         full   
497  532874347  Casual  Average     4.7     M  Summer     v-neck         full   
498  655464934  Casual  Average     4.6     L  winter  boat-neck    sleevless   
499  919930954  Casual      Low     4.4  free  Summer     v-neck        short   

    waiseline  Material  FabricType Decoration Pattern Type  Recommendation  
495   natural  polyster        None       None        solid               1  
496    empire    cotton        None       None         None               0  
497    empire    cotton        None       lace        solid               1  
498    empire      silk  broadcloth   applique        print               1  
499    empire    cotton    Corduroy       lace        solid               0

In [91]:
sales_df_json = pd.read_csv('../../FSDS_DATA_SET/sales.csv')
sales_df_json.fillna(-1)
sales_df_json.head()

Dress_ID  29/8/2013  31/8/2013  2013-02-09 00:00:00  2013-04-09 00:00:00  \
0  1006032852       2114       2274                 2491                 2660   
1  1212192089        151        275                  570                  750   
2  1190380701          6          7                    7                    7   
3   966005983       1005       1128                 1326                 1455   
4   876339541        996       1175                 1304                 1396   

   2013-06-09 00:00:00  2013-08-09 00:00:00  2013-10-09 00:00:00  \
0                 2727                 2887                 2930   
1                  813                 1066                 1164   
2                    8                    8                    9   
3                 1507                 1621                 1637   
4                 1432                 1559                 1570   

  2013-12-09 00:00:00 14/9/2013  ... 24/9/2013 26/9/2013 28/9/2013 30/9/2013  \
0                3119      3204  ...      3554    3624.0      3706    3746.0   
1                1558      1756  ...      2710    2942.0      3258    3354.0   
2                  10        10  ...        11      11.0        11      11.0   
3                1723      1746  ...      1878    1892.0      1914    1924.0   
4                1638      1655  ...      2032    2156.0      2252    2312.0   

   2013-02-10 00:00:00  2013-04-10 00:00:00  2013-06-10 00:00:00  \
0               3795.0               3832.0                 3897   
1               3475.0               3654.0                 3911   
2                 11.0                 11.0                   11   
3               1929.0               1941.0                 1952   
4               2387.0               2459.0                 2544   

   2010-08-10 00:00:00  2013-10-10 00:00:00  2013-12-10 00:00:00  
0               3923.0               3985.0                 4048  
1               4024.0               4125.0                 4277  
2                 11.0                 11.0                   11  
3               1955.0               1959.0                 1963  
4               2614.0               2693.0                 2736  

[5 rows x 24 columns]

In [92]:
# CONVERTING SALES DATASET INTO JSON FILE

sales_df_json.to_json('../../FSDS_DATA_SET/sales.json')

In [93]:
sales_json = pd.read_json('../../FSDS_DATA_SET/sales.json')

In [94]:
sales_json.tail(6)

Dress_ID  29/8/2013  31/8/2013  2013-02-09 00:00:00  \
494  990559192          0          0                    0   
495  713391965          0          0                    0   
496  722565148          0          0                    0   
497  532874347          0          0                    0   
498  655464934          0          0                    0   
499  919930954          0          0                    0   

     2013-04-09 00:00:00  2013-06-09 00:00:00  2013-08-09 00:00:00  \
494                   60                   62                   64   
495                  560                  554                  544   
496                  875                  866                  861   
497                  734                  728                  726   
498                  254                  259                  261   
499                  538                  545                  558   

     2013-10-09 00:00:00 2013-12-09 00:00:00 14/9/2013  ... 24/9/2013  \
494                   65                  67        68  ...        73   
495                  537                 525       519  ...       400   
496                  854                 850       844  ...       859   
497                  715                 694       690  ...       616   
498                  263                 268       270  ...       257   
499                  563                 578       585  ...       628   

    26/9/2013 28/9/2013 30/9/2013  2013-02-10 00:00:00  2013-04-10 00:00:00  \
494      74.0        75      75.0                 76.0                 76.0   
495     388.0       360     364.0                372.0                377.0   
496     866.0       882     888.0                895.0                898.0   
497     597.0       586     569.0                561.0                555.0   
498     256.0       255     254.0                253.0                250.0   
499     632.0       639     645.0                651.0                655.0   

     2013-06-10 00:00:00  2010-08-10 00:00:00  2013-10-10 00:00:00  \
494                   77                 77.0                 77.0   
495                  380                382.0                384.0   
496                  906                913.0                919.0   
497                  551                546.0                535.0   
498                  249                249.0                249.0   
499                  660                668.0                674.0   

     2013-12-10 00:00:00  
494                   77  
495                  285  
496                  931  
497                  520  
498                  248  
499                  680  

[6 rows x 24 columns]

In [95]:
# CONNECTING TO MONGODB ATLAS
try:
    client = pymongo.MongoClient("mongodb+srv://<your password>:ineuron@cluster0.ex1ru.mongodb.net/?retryWrites=true&w=majority")
except Exception as e:
    print("Error => {e}")
db = client.test

In [96]:
# CREATING A DATABASE 'dress' and a new collections 'sales' ans 'attribute' in 'dress' db
try:
    database = client['dress']
    collection = database['sales']
    collection_attribute = database['attribute']
except Exception as e:
    print("Error in creating database and collection [dress,sales]")
    print(f"Error => {e}")

In [129]:
# # Data is inserted into mongoDb
# collection.insert_many(sales_dict)

In [102]:
# all_records = collection.find()

In [107]:
# all_records

In [123]:
with open('../../FSDS_DATA_SET/sales.json') as file:
    file_data = json.load(file)

In [137]:
with open('../../FSDS_DATA_SET/attribute.json') as file:
    attr_data = json.load(file)

In [133]:
sales_json.index =  sales_json.index.map(str)

In [138]:

sales_dict =sales_json.to_dict('index')
# sales_dict

In [139]:
# Data is inserted into mongoDb
# collection.insert_one(sales_dict)

In [142]:
attr_df_json.index = attr_df_json.index.map(str)

In [143]:
attribute_dict = attr_df_json.to_dict('index')
# attribute_dict

In [145]:
# Attribute Data is inserted into mongoDb
# collection_attribute.insert_one(attribute_dict)

In [152]:
from IPython.display import Image
  
# get the image
Image(url="./Screenshot 2022-07-29 at 1.07.13 AM.png", width=1100, height=700)

In [153]:
Image(url="./Screenshot 2022-07-29 at 1.08.36 AM.png", width=1100, height=700)